config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#new"
  resources :events
  resources :schools
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :school, optional: true
  has_one :image, dependent: :destroy
  accepts_nested_attributes_for :image
  accepts_attachments_for :image, attachment: :image

  validates :name, presence: true
  validates :school_id, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  attachment :image
  belongs_to :event
end

app/models/school.rb
class School < ApplicationRecord
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :destroy]

  def new
    @event = Event.new
    @event.build_image
    @school = School.new
  end

  def create
    school = School.create(school_params) unless school_params[:name] == ""
    event = Event.new(event_params)
    event.school_id = school.id unless school_params[:name] == ""
    if event.save
      redirect_to event_path(event.id), notice: "イベントを登録しました"
    else
      flash[:notice] = "登録に失敗しました"
      render :new
    end
  end

  def index
    @events = Event.all.includes([:school, :image]).order("created_at ASC").page(params[:page]).per(10)
  end

  def show
  end

  def edit
    @school = School.new
  end

  def update
    school = School.create(school_params) unless school_params[:name] == ""
    @event = Event.includes([:school, :image]).find(params[:id])
    @event.school_id = school.id unless school_params[:name] == ""
    if @event.update(event_params)
      redirect_to event_path(@event.id), notice: "イベントを編集しました"
    else
      flash[:notice] = "編集に失敗しました"
      render :edit
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_path, notice: "イベントを削除しました"
    else
      flash[:notice] = "削除に失敗しました"
      render :show
    end
  end

  private

  def event_params
    params.require(:event).permit(
      :name,
      :school_id,
      :web_public,
      :public_start_date,
      :public_end_date,
      :remarks,
      image_attributes: [
      :id,
      :image,
      :image_cache_id
      ]
    )
  end

  def school_params
    params.require(:school).permit(:name)
  end

  def set_event
    @event = Event.includes([:school, :image]).find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def web_public_display_conversion(event)
    case event.web_public
    when "0" then
      "有"
    when "1" then
      "無"
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/events/_footer.html.haml
.footer
  %p.footer_message
    ポートフォリオご覧いただきありがとうございます。
    %br
    機能などの説明は以下になります。
    %br
    前職での経験から、業務アプリのような見た目になっています。
    %br
    完成度低いですが、随時改修していきたいと思います。
  %table
    %tr
      %th アプリ
      %td イベント登録アプリ
    %tr
      %th 関連URL
      %td
        Github:
        = link_to "https://github.com/tnaoyak/event_registration", "https://github.com/tnaoyak/event_registration", class: "footer_url"
        %br
        Qiita:
        = link_to "https://qiita.com/NT90957869", "https://qiita.com/NT90957869", class: "footer_url"
    %tr
      %th 制作期間
      %td 約12日
    %tr
      %th 使用した技術
      %td
        %p
          Ruby, Ruby on Rails, Haml, sass, jQuery
          %br
          MySQL, refile, AWS S3, Git, Github, RSpec
          %br
          jQueryValidationプラグイン, flatpickr
          %br
          tablesorter.js, materialize.css
    %tr
      %th 工夫した技術
      %td
        %p
          1) テキストフィールド, テキストエリア, プルダウンセレクト,
          %br
          チェックボックス,ラジオボタン, ファイルアップロード, ボタン,
          %br
          の７つの機能を実装
          %br
          %br
          2) 画像アップロードにrefileを使用し、画像はAWS S3へアップロード
          %br
          %br
          3) jQueryValidationプラグインによるフォームバリデーション、エラーメッセージ表示
          %br
          %br
          4) flatpickrを導入し、カレンダー形式での日付選択
          %br
          %br
          5) 画像選択後、選択した画像のサムネイルを表示
          %br
          %br
          6) イベント情報と画像を別テーブルに保存するためにfields_forを使用
          %br
          refileを使用したファイルアップロードと組み合わせて動く記述を書くため、トライ＆エラーを繰り返した
          %br
          %br
          7) メディアクエリを利用したレスポンシブ対応
          %br
          （PC、スマホサイズのみ）
          %br
          %br
          8) tablesorter.jsを使用したテーブルソート機能
          %br
          %br
          9) materialize.cssを使用したマテリアルデザイン風
    %tr
      %th 工夫した動作
      %td
        %p
          1) 「学校を新規登録する」にチェックを入れると学校を新規登録するフォームが出現する。
          %br
          「学校を新規登録する」にチェックを入れた場合は選択した学校名は登録されず、選択欄の編集もできない。
          %br
          %br
          2) 「WEB公開」のチェックを「有」にすると公開日選択フォームが入力可能になり、
          %br
          「無」の時はグレーアウト、入力不可になる。DBへの登録もされない。
          %br
          %br
          3) 「WEB公開日」の「公開終了を1ヶ月後に設定」をチェックすると、「終了日」が「開始日」の1ヶ月後になる
          %br
          %br
          4) 登録、編集完了時にフラッシュメッセージを表示
          %br
          %br
          5) 一覧ページは表形式で表示
          %br
          %br
          6) 一覧ページで学校名orIDをクリックすると詳細画面へ。詳細画面では編集、削除が可能。
          %br
          %br
          7) 一覧ページで見出しをマウスオーバーするとソートマークが現れる

app/views/events/_form.html.haml
.event-form
  = form_with model: @event, html: { class: "event-form-content" } do |f|
    .form-group
      = f.label :name, "イベント名", class: "form-label"
      .name_field
        = f.text_field :name, placeholder: "イベント名を入力", class: "input-field browser-default", value: "#{event.name}"
    .form-group
      = f.label :school_id, "学校名", class: "form-label"
      .select-wrap
        = f.collection_select(:school_id, School.all, :id, :name, { prompt: "" } , { class: "select-default browser-default", id: "school_select", value: "#{event.school&.name}"} )
        .new-school-check
          %label.checkbox
            %input{ type: "checkbox", name: "public-period", id: "new_school_check_box", class: "filled-in"}
            %label.checkbox--area{ for: "new_school_check_box" }
            %span.checkbox--text 学校を新規登録する
    = fields_for @school do |s|
      .form-group.new_school
        = s.label :name, "新規学校名", class: "form-label"
        .name_field
          = s.text_field :name, placeholder: "新規学校名を入力", class: "input-field browser-default"
      #school_name_error
    .form-group
      %label.form-label web公開
      .radio-button-wrap.valign-wrapper
        = f.radio_button :web_public, "0", value: "0", class: "radio-button with-gap", id: "web_public_presence"
        %label.radio-button--text{for: "web_public_presence"} 有
        = f.radio_button :web_public, "1", value: "1", class: "radio-button with-gap", id: "web_public_none"
        %label.radio-button--text.back{for: "web_public_none"} 無
        = f.hidden_field :public_start_date, id: "public_start_date_hidden", value: "#{event.public_start_date}"
        = f.hidden_field :public_end_date, id: "public_end_date_hidden", value: "#{event.public_end_date}"
    .form-group.public-wrap
      %label.form-label.public-wrap__label web公開日
      .public-wrap__form
        .public-wrap__start_date-form
          = f.label :public_start_date, "開始日", class: "public-wrap__title"
          = f.text_field :public_start_date,{ type: "text", id: "public-wrap__start-date", class: "public-wrap__date browser-default", value: "#{event.public_start_date}"}
          %span.public-wrap__wave-line 〜
        .public-wrap__end_date-form
          = f.label :public_end_date, "終了日", class: "public-wrap__title"
          = f.text_field :public_end_date, type: "text", id: "public-wrap__end-date", class: "public-wrap__date browser-default", value: "#{event.public_end_date}"
      .public-period.xl-size
        %label.checkbox
          %input{ type: "checkbox", name: "public-period", id: "public-period__checkbox", class: "filled-in" }
          %label.checkbox--area{ for: "public-period__checkbox" }
          %span.checkbox--text 公開終了を1ヶ月後に設定
    .form-group
      = f.fields_for :image do |i|
        .form-label 画像を選択
        = i.attachment_field :image, id: "drop_area", class: "input-field image-field", value: "#{event.image}"
        = i.label :image, "クリックして選択", for: "drop_area", class: "image-input-field", id: "img_field"
        - if event.image.id
          .form-label.saved_image_title 保存済み画像
          .saved_image_area
            = attachment_image_tag event.image, :image, :fill, 200, 120, format: "jpg"
    .form-group
      = f.label :remarks, "備考", class: "form-label"
      = f.text_area :remarks, placeholder: "補足事項など", class: "input-field text-area", value: "#{event.remarks}"
    .btn-area
      = f.submit "登録", class: "waves-effect waves-light btn cyan lighten-2 registration-btn"

app/views/events/_nav_panel.html.haml
.nav-panel.z-depth-2
  .collection.z-depth-2
    = link_to "イベント登録", root_path, class: "collection-item"
    = link_to "イベント一覧", events_path, class: "collection-item"
  .search-area
    .search-area__text イベント検索
    .= search_field 

app/views/events/edit.html.haml
.main-area
  = render partial: 'nav_panel'
  .content
    .content__head
      %h4 イベント編集
    = render "form", event: @event

app/views/events/index.html.haml
.main-area
  = render partial: 'nav_panel'
  .content
    .content__head
      %h4 イベント一覧
    .index-area.xl-size
      %table.event-index.striped.tablesorter#index-table-tablesorter
        %thead
          %tr
            %th
              .event-index__title イベントID
              %i.fas.fa-sort
            %th
              .event-index__title イベント名
              %i.fas.fa-sort
            %th
              .event-index__title 学校名
              %i.fas.fa-sort
            %th
              .event-index__title WEB公開
              %i.fas.fa-sort
            %th
              .event-index__title 公開開始日
              %i.fas.fa-sort
            %th
              .event-index__title 公開終了日
              %i.fas.fa-sort
          %tbody
          - @events.each do |event|
            %tr.event-index__content
              %td.event-index__content--event_id.table-num
                = link_to "#{event.id}", event_path(event.id)
              %td.event-index__content--event_name
                = link_to "#{event.name}", event_path(event.id)
              %td.event-index__content--school_name
                = event.school.name
              %td.event-index__content--web_public
                = web_public_display_conversion(event)
              %td.event-index__content--public_start_date.table-num
                = event.public_start_date
              %td.event-index__content--public_end_date.table-num
                = event.public_end_date
      .paginate.center-align
        = paginate(@events)

    .index-area.sm-size
      - @events.each do |event|
        %table.event-index.striped
          %tr.event-index__title
            %th.event-index__title--event_id イベントID
            %td.event-index__content--event_id
              = link_to "#{event.id}", event_path(event.id)
          %tr.event-index__title
            %th.event-index__title--event_name イベント名
            %td.event-index__content--event_name
              = link_to "#{event.name}", event_path(event.id)
          %tr.event-index__title
            %th.event-index__title--school_name 学校名
            %td.event-index__content--school_name
              = event.school.name
          %tr.event-index__title
            %th.event-index__title--web_public WEB公開
            %td.event-index__content--web_public
              = web_public_display_conversion(event)
          %tr.event-index__title
            %th.event-index__title--public_start_date 公開開始日
            %td.event-index__content--public_start_date
              = event.public_start_date
          %tr.event-index__title
            %th.event-index__title--public_end_date 公開終了日
            %td.event-index__content--public_end_date
              = event.public_end_date
      .paginate
        = paginate(@events)

app/views/events/new.html.haml
.main-area
  = render partial: 'nav_panel'
  .content
    .content__head
      %h4 イベント登録
    = render "form", event: @event

app/views/events/show.html.haml
.main-area
  = render partial: 'nav_panel'
  .content
    .content__head
      %h4 イベント詳細
    .show-are.xl-size
      %table.event-index.striped
        %tr
          %th.event-index__title--event_id イベントID
          %th.event-index__title--event_name イベント名
          %th.event-index__title--school_name 学校名
          %th.event-index__title--web_public WEB公開
          %th.event-index__title--public_start_date 公開開始日
          %th.event-index__title--public_end_date 公開終了日
        %tr.event-index__content
          %td.event-index__content--event_id.table-num
            = link_to "#{@event.id}", event_path(@event.id)
          %td.event-index__content--event_name
            = link_to "#{@event.name}", event_path(@event.id)
          %td.event-index__content--school_name
            = @event.school.name
          %td.event-index__content--web_public
            = web_public_display_conversion(@event)
          %td.event-index__content--public_start_date.table-num
            = @event.public_start_date
          %td.event-index__content--public_end_date.table-num
            = @event.public_end_date
      %table.event-show.striped
        %tr.event-show__title
          %th.event-show__title--image 画像
          %th.event-show__title--remarks 備考
        %tr.event-show__content
          %td.event-show__content--image
            = attachment_image_tag @event.image, :image, :fill, 300, 300, format: "jpg"
          %td.event-show__content--remarks
            = @event.remarks
      .event-form__edit-link
        = link_to "編集", edit_event_path(@event.id), class: "waves-effect waves-light btn cyan lighten-"
        = link_to "削除", "/events/#{@event.id}", method: :delete, class: "waves-effect waves-light btn cyan lighten-"

    .event-form.sm-size
      %table.event-index.striped
        %tr.event-index__title
          %th.event-index__title--event_id イベントID
          %td.event-index__content--event_id
            = link_to "#{@event.id}", event_path(@event.id)
        %tr.event-index__title
          %th.event-index__title--event_name イベント名
          %td.event-index__content--event_name
            = link_to "#{@event.name}", event_path(@event.id)
        %tr.event-index__title
          %th.event-index__title--school_name 学校名
          %td.event-index__content--school_name
            = @event.school.name
        %tr.event-index__title
          %th.event-index__title--web_public WEB公開
          %td.event-index__content--web_public
            = web_public_display_conversion(@event)
        %tr.event-index__title
          %th.event-index__title--public_start_date 公開開始日
          %td.event-index__content--public_start_date
            = @event.public_start_date
        %tr.event-index__title
          %th.event-index__title--public_end_date 公開終了日
          %td.event-index__content--public_end_date
            = @event.public_end_date
      %table.event-show.striped
        %tr.event-show__title
          %th.event-show__title--image 画像
        %tr.event-show__content
          %td.event-show__content--image
            = attachment_image_tag @event.image, :image, :fill, 200, 200, format: "jpg"
        %tr.event-show__title
          %th.event-show__title--remarks 備考
        %tr.event-show__content
          %td.event-show__content--remarks
            = @event.remarks
      .event-form__edit-link
        = link_to "編集", edit_event_path(@event.id), class: "waves-effect waves-light btn cyan lighten-"
        = link_to "削除", "/events/#{@event.id}", method: :delete, class: "waves-effect waves-light btn cyan lighten-"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title EventRegistration
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link(rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous")

    // Google Web Fonts Noto Sans JP
    %link(href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet")

    // flatpickr導入
    %link(rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css")
    %script(src="https://unpkg.com/flatpickr")
    %script(src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js")
    // スタイル選択
    %link(rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/material_blue.css")
    // IE9対応
    %link(rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/ie.css")

    // tablesorter.js導入
    %script(type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.1/js/jquery.tablesorter.min.js")

    // Materialize導入
    %link(href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet")
    %link(rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css")
    %script(src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js")

  %body
    -if flash[:notice]
      .flash
        = flash[:notice]
    %nav.teal
      .nav-wrapper
        = link_to "イベント登録アプリ", root_path, class: "brand-logo center"
    = yield
    = render partial: 'footer'